package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"Prak_11/graph/model"
	"Prak_11/internal/store"
	"context"
	"fmt"
)

func fromStore(t *store.Task) *model.Task {
	return &model.Task{
		ID:          t.ID,
		Title:       t.Title,
		Description: t.Description,
		Done:        t.Done,
	}
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, input model.CreateTaskInput) (*model.Task, error) {
	//panic(fmt.Errorf("not implemented: CreateTask - createTask"))
	if input.Title == "" {
		return nil, fmt.Errorf("title is required")
	}
	t := r.Store.Create(input.Title, input.Description)
	return fromStore(t), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, input model.UpdateTaskInput) (*model.Task, error) {
	//panic(fmt.Errorf("not implemented: UpdateTask - updateTask"))
	t, err := r.Store.Update(id, input.Title, input.Description, input.Done)
	if err != nil {
		return nil, fmt.Errorf("task not found")
	}
	return fromStore(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	//panic(fmt.Errorf("not implemented: DeleteTask - deleteTask"))
	ok := r.Store.Delete(id)
	return ok, nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context) ([]*model.Task, error) {
	//panic(fmt.Errorf("not implemented: Tasks - tasks"))
	all := r.Store.All()
	result := make([]*model.Task, 0, len(all))
	for _, t := range all {
		result = append(result, fromStore(t))
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*model.Task, error) {
	//panic(fmt.Errorf("not implemented: Task - task"))
	t, err := r.Store.GetByID(id)
	if err != nil {
		return nil, nil // return null to client
	}
	return fromStore(t), nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
